num = str(input('inform a number: '))
print ('Analizando o número {}'.format(num))
print ('Unidade: {}'.format(num[3]))
print ('Dezena: {}'.format(num[2]))
print ('Centena: {}'.format(num[1]))
print ('Milhar: {}'.format(num[0]))
